apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-tracker-api
  name: simple-tracker-api
spec:
  containers:
  - image: ghcr.io/boxboat-github-practice/simple-tracker-express-api:20230331.11
    name: simple-tracker-api
    resources: {}
    volumeMounts:
    - name: config
      mountPath: "/app/config.json"
      subPath: config.json
      readOnly: true
    env:
    - name: DB_SERVER
      value: "boxboat-demo-sql.database.windows.net"
    - name: AZURE
      value: "true"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: config
    secret:
      secretName: config.json
      items: 
      - key: config.json
        path: config.json
