apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-tracker-api
  name: simple-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-tracker-api
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-tracker-api
    spec:
      containers:
      - image: ghcr.io/boxboat-github-practice/simple-tracker-express-api:20230331.13
        name: simple-tracker-api
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/app/config.json"
          subPath: config.json
          readOnly: true
        env:
        - name: DB_SERVER
          value: "boxboat-demo-sql.database.windows.net"
        - name: AZURE
          value: "true"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes: 
      - name: config
        secret:
          secretName: config.json
          items: 
          - key: config.json
            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-tracker-api
  name: simple-tracker-api
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: simple-tracker-api
  type: ClusterIP
