apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-tracker-api
  name: simple-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-tracker-api
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-tracker-api
    spec:
      containers:
      - image: ghcr.io/boxboat-github-practice/simple-tracker-express-api:20230331.16
        name: simple-tracker-api
        resources: {}
        env:
        - name: DB_SERVER
          value: "boxboat-demo-sql.database.windows.net"
        - name: DB_NAME
          value: "acctest-db-d"
        - name: DB_USER
          value: "blinky"
        - name: DB_PASS
          valueFrom: 
            secretKeyRef:
              name: dbpass
              key: pass
        - name: AZURE
          value: "true"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-tracker-api
  name: simple-tracker-api
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: simple-tracker-api
  type: ClusterIP
